### ISSUE TITLE
Badges do not show the branch status for Github projects

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#4051] opened 2020-12-07 17:48 UTC
**Describe the bug**

Badges do not work on Github projects.

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/api/github/v1/repository/mozilla-mobile/android-components/master/badge.svg.
2. Observe the 'no info yet' on the SVG.
2. Observe the 404 response in the `message` on https://firefox-ci-tc.services.mozilla.com/api/github/v1/repository/mozilla-mobile/android-components/master/latest.

The output copied over to the bug:
```json
{
  "code": "ResourceNotFound",
  "message": "Status not found\n\n---\n\n* method:     latest\n* errorCode:  ResourceNotFound\n* statusCode: 404\n* time:       2020-12-07T17:42:58.297Z",
  "requestInfo": {
    "method": "latest",
    "params": {
      "owner": "mozilla-mobile",
      "repo": "android-components",
      "branch": "master"
    },
    "payload": {},
    "time": "2020-12-07T17:42:58.297Z"
  }
}
```

**Expected behavior**
 - The appropriate badge output (red/green) depending on the build.

**Taskcluster version**

38.0.6

**Screenshots**

**Platform (please complete the following information):**

n/a

**Additional context**

I'm unsure if this an issue with the `firefox-ci-tc.services.mozilla.com` instance configuration or a general TC issue. Reporting here, but please move to the correct component otherwise.

**Comment by djmitche** [comment] 2020-12-07 23:27
I think this is #3362.

**Comment by djmitche** [comment] 2020-12-07 23:27
I don't know why I submitted that comment before I checked.  It is a duplicate of #3362 :)

**Closed by djmitche** 2020-12-07 23:27 UTC
Labels: bug
