### ISSUE TITLE
Github checks are completing on TaskCluster but staying queued in Github

### ISSUE THREAD

**Issue by LukeZielinski** [taskcluster/taskcluster#4074] opened 2020-12-09 16:38 UTC
**Describe the bug**
In the WPT repo, we have several checks that schedule TaskCluster tasks. The tasks all run successfully in Taskcluster but sometimes, some of them are left "queued" on the Github side. The effect is that PRs remain in a pending state. Retrying the checks (by closing/reopening the PR) often works.

**To Reproduce**
This is happening inconsistently, but one recent example is SHA [2a32848](https://github.com/web-platform-tests/wpt/commit/2a32848ae0f2bbc07ed046a6a343fd488aaf98d6)
The checks for this commit appear as "queued" in Github but clicking through to TaskCluster, they appear to have completed (https://community-tc.services.mozilla.com/tasks/groups/JMVKDMPoRnCMZLts29LAkA)

Another example SHA is [d98e17b](https://github.com/web-platform-tests/wpt/commit/d98e17bd646fa0e5ca4e6a8ef9f4cf7b20c0ac53)

**Expected behavior**
Completion of tasks in TaskCluster should be communicated to Github.

**Taskcluster version**
39.0.0

**Platform (please complete the following information):**
 - OS: Linux
 - Browser if applicable: Firefox, Chrome

**Comment by djmitche** [comment] 2020-12-09 18:02
@imbstack can you take a look?  I wonder if this is related to the `ext` errors?

**Comment by imbstack** [comment] 2020-12-09 22:25
I can see in the logs that we're hit with a good handful of [those errors](https://sentry.prod.mozaws.net/operations/taskcluster-community/issues/10211271) (`'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires` for those without access to our sentry). I believe this is clock skew stuff and our token generation never took this into account (not sure how we didn't get bit before now). I'll test my fix from that PR now

**Comment by LukeZielinski** [comment] 2020-12-11 14:24
Hi I see that this happened again yesterday (about ~3h after the fix landed) [5bde9c8](https://github.com/web-platform-tests/wpt/commit/5bde9c804c5518203cd4ed2fefafc7638a382ce5). Would the change apply immediately or is there a release process we need to wait for?

Thanks!

**Comment by djmitche** [comment] 2020-12-11 14:35
There's a release process.  I'm not sure just yet what the schedule is to get 39.1.0 deployed on community, but hopefully soon :)

**Comment by imbstack** [comment] 2020-12-11 22:15
I believe this is actually caused by something else and will be fixed by a fix for #3797

**Comment by st3fan** [comment] 2020-12-14 02:33
Hey folks, just a note from the Android Components team that this is a disruption around our workflow. We have a lot of automation around PRs, which is currently not running because the checks don't update.

See the last few at https://github.com/mozilla-mobile/android-components/pulls

It seems all our PRs since Friday are now suffering from this problem - did something change around that time? We've never seen this issue before.

**Comment by imbstack** [comment] 2020-12-15 03:50
I believe this has been resolved (deployed as well) today in #4107. Please re-open if there are still things misbehaving!

**Closed by imbstack** 2020-12-15 03:50 UTC
Labels: bug
