### ISSUE TITLE
No "parent folder" navigation in the index browser

### ISSUE THREAD

**Issue by mstange** [taskcluster/taskcluster#2419] opened 2020-02-26 16:47 UTC
If I'm at https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly I can click subfolders to make my way down to the file I'm looking for, and I can use the browser's back button to go back up the folder structure. But if I start at https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly.2020.02.26/latest I don't know how to go back up other than by manually editing the URL.

**Comment by helfi92** [comment] 2020-02-26 19:31
Duplicate of https://github.com/taskcluster/taskcluster/issues/1389.

Another workaround you can use for now until that issue is resolved is to edit the value of the search component:

![Screen Shot 2020-02-26 at 2 29 51 PM](https://user-images.githubusercontent.com/3766511/75380124-7a6bfe00-58a4-11ea-9212-8d4016236808.png)

**Closed by helfi92** 2020-02-26 19:31 UTC
