### ISSUE TITLE
worker-manager: Azure workers register when state != REQUESTED

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#4999] opened 2021-10-07 19:09 UTC
**Describe the bug**

About 100 times a day, the worker-manager for Firefox-CI logs the error "Worker was already running.". This is from the `register()` method for the Azure provider:

https://github.com/taskcluster/taskcluster/blob/685a0470d6ddb845552f33c245a18503c990c634/services/worker-manager/src/providers/azure/index.js#L620-L623

**To Reproduce**

In the GCP log explorer for the Firefox-CI project, filter with:

```
labels.k8s-pod/app_kubernetes_io/component="taskcluster-worker-manager-web"
jsonPayload.Type="registration-error-warning"
```

**Expected behavior**

Workers should only register in the ``REQUESTED`` state. They could re-register, but that is a different endpoint.

The log message assumes the worker is in the ``RUNNING`` state, but does not provide enough information to determine the actual state.

**Taskcluster version**

Firefox CI is running 43.2.0. This is probably present in the current main branch and community-tc, but there are no Azure worker pools in community-tc.

**Comment by lotas** [comment] 2022-03-15 14:14
Debugging one of those issues, found that this error happens right after worker was removed (or marked for removal):
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/83861/158397017-65de1dfc-e94f-4fb8-afa5-4ece7c57df86.png">

**Comment by lotas** [comment] 2022-03-15 18:23
after following logs for couple of such VMs, they all follow similar pattern: (timing approximate)

* `t+0` - `worker-requested` - provisioner is creating new instance
* `t+22min` - `"vm instance view not found"`  - worker-scanner is doing `checkWorker()` and `queryInstance()`
* right after: `"provisioning resource` - `azure.checkWorker()` + `azure.provisionResource()`
* `t+90min` - same as above - `"vm instance view not found"`
* `t+120min` - same as above -`"vm instance view not found"`
* `t+121min` - `"fetched instance view"` - instance is in the `running` state, but  `"worker-removed"` says  that `"terminateAfter time exceeded"`
and the last one is coming either from `DELETE /workers/../../..` call or from `worker-scanner's` `azure.checkWorker()`

So as I understand it instances are being created, after ~2 hours are being terminated because of `terminateAfter` flag on the instance says it should be terminated regardless of the state

https://github.com/taskcluster/taskcluster/blob/main/services/worker-manager/src/providers/azure/index.js#L1042-L1047

**Questions:**
1. is this `terminateAfter` time set properly?
2. is it okay that some instances fail to start in under 2h on azure, so can be ignored?
3. where to find the actual values for `terminateAfter`? (Maybe adding this to the logs would make sense)

**Comment by djmitche** [comment] 2022-03-15 21:56
The lifecycle comes from [here](https://firefox-ci-tc.services.mozilla.com/worker-manager/comm-t%2Fwin10-64-2004)
```
  "lifecycle": {
    "registrationTimeout": 1800,
    "reregistrationTimeout": 345600
  },
```
but curiously, 1800 is 30 minutes, not 2 hours (and 345600 is 4 days).  I apologize for the really similar names :(  The shorter time should be the maximum time until the `registerWorker` API method is called, and that timer should start before the VM (or NIC or IP or disks) is created.  Then the longer time is the time within which the `reregisterWorker` API method must be called, starting after the `registerWorker` call.

I don't think "less than 2 hours" is an unreasonable expectation for starting a VM.  I've worked with cloud vendors which I'm _pretty_ sure were printing API requests on thermal paper and sending remote hands into the racks, and _they_ could spin up a system in less than 2 hours.

Adding terminateAfter to the logs makes a lot of sense.  But I suspect it's a symptom, here -- either Azure is breaking and WM should figure that out earlier, or (maybe slightly more likely) WM is doing something wrong starting the VM and either it's not starting or WM isn't recognizing that it's started.

**Comment by lotas** [comment] 2022-03-24 17:59
Was able to confirm with extra logging that `terminateAfter` is indeed +30min, but instance is being killed after ~1.5h

Termination happens during `registerWorker` api call. I need to check the correct sequence of events, but it seems as WM had requested new worker, it was created, took longer to start but status was changed to `running` before worker called `registerWorker`, which made it fail

**Comment by lotas** [comment] 2022-03-29 12:06
I'm quite sure this is caused by a delayed loop as noted here: https://github.com/taskcluster/taskcluster/issues/4987#issuecomment-1080845231 
Azure loop sometimes acts weird and takes ~2h to cycle, which would explain why by the time instance is ready to work it is being terminated instead

**Comment by lotas** [comment] 2022-04-26 11:59
So we see that overall success for Azure provisioning depends on `workerScannerAzure` times. 
It needs at least several loops to fully provision VM. Given that default timeout is `30min`, loop times greater than `15min` would most likely result in worker's failure to register within given time. 

To speed things up, resources will start to be provisioned immediately during `provisioner` loop - #5382 (just like GCP and AWS). This should reduce number of scanner loops needed to fully provision VM, and by the time it first picks worker for provisioning, it would already have 1 resource provisioned.

**Comment by lotas** [comment] 2022-05-05 14:33
I continue investigation why scanner process throws exception. One particular case was when loop stalled:

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/83861/166945567-271dae79-8a9c-48f5-88e8-e0458f3d8031.png">

last line executed was here: https://github.com/taskcluster/taskcluster/blob/v44.13.5/services/worker-manager/src/providers/azure/index.js#L880-L886

After this call it didn't return anything for the next hour or more and worker was not updated.
It seems like `this._enqueue()` was stuck in some rare condition, as there were no extra logs to tell if cloud api was being rate-limited or other kinds of errors.

**Comment by lotas** [comment] 2022-05-05 14:58
I see that `p-queue` has per-task [`timeout`](https://github.com/sindresorhus/p-queue#timeout) option, which might help here, to avoid getting stuck forever.
It is either p-queue implementation has a bug which hangs the whole process, or there is an issue with some specific provider that receives a call and keeps connection open forever.

@djmitche do you remember if this was ever an issue or concern? My gut feeling is that this could be the reason we still see those loop exceptions: loop killed after max time passed and not because there are too many slow calls that exceed total time allowed.
I think it should be safe to add per-task timeout for 5-10min or so, so we could fail the call early and retry or move on, instead of waiting 60-90min for it to be killed by `Iterate.maxIterationTime`

**Comment by lotas** [comment] 2022-05-19 08:01
Timeout fix was deployed and already one loop saved: 
<img width="823" alt="image" src="https://user-images.githubusercontent.com/83861/169243432-5411ab05-e561-4611-b618-93cde519e7ac.png">

Possibly 10min can be reduced to 5min

**Comment by lotas** [comment] 2022-05-19 08:36
I think it is not possible to fully get rid of those errors, so I will close this ticket.
Over the past months, number of such incidents were noticeably reduced, happening 5-10 times a day. 
Major issue was that Azure Provisioner/Scanner was ineffective (single resource privisioning per loop). This was mitigated by reducing number of calls needed (Public IP can be skipped + first resource provisioned from the provisioner loop, unlike scanner loop before).
Furthermore, azure was isolated from gcp/aws scanners, which improved overall stability and decreased loop times for all cloud providers.
And the latest #5436 timeout should prevent loops being stuck. 

It will still happen as workers might take longer to boot and to make initial `registerWorker` call, but less frequently

**Closed by lotas** 2022-05-19 08:36 UTC
Labels: bug, worker management
