### ISSUE TITLE
[UI] Sign In button not visible properly

### ISSUE THREAD

**Issue by bhushan-borole** [taskcluster/taskcluster#3413] opened 2020-08-18 15:18 UTC
**Describe the bug**

The sign in button is not visible properly.
And there is a lot of space on the left side of the nav bar.
Also the arrow on the left, is slightly hidden.

**To Reproduce**

1. Go to: https://community-tc.services.mozilla.com/tasks/UgHmihQXScq9V29fgpf2ZA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FUgHmihQXScq9V29fgpf2ZA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
2. Open it on a mobile browser (not toggling the mobile view on chrome).

**Expected behavior**

There can be 2 approaches to this:
1. Remove the sign in button, and it will be present in the navigation bar activity.
2. Move the nav bar button (three rectangles) and search bar to the left, so that there will be space for the sign in button

**Screenshots**

![Screenshot_20200816-083841 (1)](https://user-images.githubusercontent.com/37565807/90530262-49ed8880-e192-11ea-9616-ea57d9b76449.png)

**Platform (please complete the following information):**

 - OS: Android 9
 - Browser: Chrome
 - Version of chrome: 84.0.4147.125
- Device: Xiaomi Mi A1

**Comment by helfi92** [comment] 2020-08-18 17:13
Thank you for bringing this to our attention. This is actually a duplicate of https://github.com/taskcluster/taskcluster/issues/1670. An attempt to fix this was made in https://github.com/taskcluster/taskcluster/pull/1596. The implementation was more or less done but we're open to have someone take it to the finish line.

**Closed by helfi92** 2020-08-18 17:13 UTC
Labels: bug
