### ISSUE TITLE
The Log viewer URI decodes the artifact URL incorrectly if a bewit is specified

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#3831] opened 2020-11-02 14:52 UTC
**Describe the bug**
If a bewit is specified for a log artifact, the log viewer incorrectly decodes the artifact URL multiple times, destroying the artifact name and resulting in a 401 message.

**To Reproduce**

1. Make sure that `queue:get-artifact:public/*` is not granted to anonymous.
2. Run a task and wait for it to complete.
3. Click on the backing artifact log link.
4. (Chrome only) Notice that the page loads correctly, press F5.
5. Notice the 401 error.

**Expected behavior**
The log should be displayed correctly.

**Taskcluster version**
v38.0.1

**Screenshots**
https://i.snipboard.io/n0GZL6.jpg

**Platform (please complete the following information):**
 - OS: Windows 10
 - Chrome: 86
 - Firefox: 82.0.2

**Additional context**
The error that yields the 401 is 'Bad mac' which is caused by the URL being decoded one time too many.

**Comment by djmitche** [comment] 2020-11-03 18:02
With #3844, I get

![image](https://user-images.githubusercontent.com/28673/98023295-b3198b00-1dd4-11eb-9e69-054a672f7180.png)

(awesome!) and in the console:

```
Unhandled GraphQL subscription error Error: GraphQL error: this.innerReconcileSubscriptions is not a function
    ApolloError bundle.esm.js:63
    makeObservable bundle.esm.js:1481
    next Observable.js:322
    notifySubscription Observable.js:135
    onNotify Observable.js:179
    next Observable.js:235
    next bundle.esm.js:866
    next bundle.esm.js:866
    notifySubscription Observable.js:135
    onNotify Observable.js:179
    next Observable.js:235
    opId client.js:163
    processReceivedData client.js:532
    onmessage client.js:485
    connect client.js:483
    executeOperation client.js:261
    subscribe client.js:150
    setContext bundle.esm.js:13
    promise callback*setContext/</< bundle.esm.js:12
    Subscription Observable.js:197
    subscribe Observable.js:279
    multiplex bundle.esm.js:864
    Subscription Observable.js:197
    subscribe Observable.js:279
    map Observable.js:319
    Subscription Observable.js:197
    subscribe Observable.js:279
    subscribeToMore bundle.esm.js:264
    obsSubscribeToMore react-hooks.esm.js:92
    TaskGroup index.jsx:238
    render index.jsx:636
    React 8
    unstable_runWithPriority scheduler.development.js:653
    React 2
    workLoop scheduler.development.js:597
    flushWork scheduler.development.js:552
    performWorkUntilDeadline scheduler.development.js:164
    EventHandlerNonNull* scheduler.development.js:187
    <anonymous> scheduler.development.js:857
    js vendors~docs~index.js:10379
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    <anonymous> index.js:6
    js vendors~docs~index.js:10391
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    React 2
    js vendors~docs~index.js:9844
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    <anonymous> React
    js vendors~docs~index.js:9856
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    <anonymous> index.jsx:4
    jsx index.js:23
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    0 index.js:168
    __webpack_require__ runtime.js:854
    checkDeferredModules runtime.js:46
    webpackJsonpCallback runtime.js:33
    <anonymous> index.js:1
console.js:176:23
```

**Comment by djmitche** [comment] 2020-11-03 18:07
The `[object Object]` thing was a bug in that PR, now fixed.  Now:

![image](https://user-images.githubusercontent.com/28673/98023757-64202580-1dd5-11eb-994d-53afb103d5c4.png)

so I think this is fixed by #3844.  The subscription error is a different issue :)

**Comment by djmitche** [comment] 2020-11-03 18:24
Oh, I reproduced this incorrectly -- this bug may still exist.  Sorry for the noise!  Back to you @petemoore

**Comment by ricky26** [comment] 2020-11-03 20:37
@djmitche, it looks like this was closed prematurely (based on your comment from #3844).

**Comment by djmitche** [comment] 2020-11-03 20:44
Oh good spot, I thought I removed that link.

**Comment by djmitche** [comment] 2020-11-04 22:02
I can reproduce this in my dev environment with a full anonymous role (not that surprising -- it's a 401, not a 403, so scopes are not consulted)

**Comment by djmitche** [comment] 2020-11-04 22:12
Also, this seems to only be an issue with live logs

**Comment by ricky26** [comment] 2020-11-04 23:04
We're reliably seeing it with the backing log too (if I read the code correctly that'd still be the other code path).

**Comment by djmitche** [comment] 2020-11-06 15:57
I'll steal this since Pete's out sick.  And will continue to try to characterize the issue :)

**Comment by djmitche** [comment] 2020-11-06 16:43
OK, I'm reproducing in https://dustin-dev.taskcluster.net, which is currently running 38.0.1.  I've removed the `queue:get-artifact:public/*` scope from anonymous, and logged in as a user without that scope.  I'm looking at https://dustin.taskcluster-dev.net/tasks/WNfX_ZHtSaO-rarvsP2hOg#artifacts.

Clicking on the backing log artifact gives me a 403:
```
Forbidden (HTTP 403)
An error occurred attempting to load the provided log.
Please check the URL and ensure it is reachable.
https://dustin.taskcluster-dev.net/api/queue/v1/task/WNfX_ZHtSaO-rarvsP2hOg/runs/0/artifacts/public%2Flogs%2Flive_backing.log?bewit=Z2l0aHViLzI4NjczfGRqbWl0Y2hlXDE2MDQ2ODE2Mjhcc3M1YzlhdWIwMmhyZk01Rlg0RjFLVWljWE94WUk1YnlmclpOOHdXQXhNbz1cZXlKalpYSjBhV1pwWTJGMFpTSTZleUoyWlhKemFXOXVJam94TENKelkyOXdaWE1pT2xzaVlYTnpkVzFsT214dloybHVMV2xrWlc1MGFYUjVPbWRwZEdoMVlpOHlPRFkzTTN4a2FtMXBkR05vWlNKZExDSnpkR0Z5ZENJNk1UWXdORFkzT1RVMU16TXlNeXdpWlhod2FYSjVJam94TmpBME5qZ3hNelV6TXpJekxDSnpaV1ZrSWpvaU1GTXpVV2x5V21kVVkwOVRVakZoV2t4a1QyMUJaMFpqZEhCaWJscGhVamQ1V1dRM1YzWlFSakZ3WkZFaUxDSnphV2R1WVhSMWNtVWlPaUpzVFVsaVdtUlhiR3g0YzJka1RYSTVRbE5qVjFVMU1XVTJiRWsyVW5SdWNqSTNla3QyZEdwTlFtZFZQU0lzSW1semMzVmxjaUk2SW5OMFlYUnBZeTkwWVhOclkyeDFjM1JsY2k5M1pXSXRjMlZ5ZG1WeUluMTk
```

Reloading that gives a 401:
```
Unauthorized (HTTP 401)
An error occurred attempting to load the provided log.
Please check the URL and ensure it is reachable.
https://dustin.taskcluster-dev.net/api/queue/v1/task/WNfX_ZHtSaO-rarvsP2hOg/runs/0/artifacts/public/logs/live_backing.log?bewit=Z2l0aHViLzI4NjczfGRqbWl0Y2hlXDE2MDQ2ODE2Mjhcc3M1YzlhdWIwMmhyZk01Rlg0RjFLVWljWE94WUk1YnlmclpOOHdXQXhNbz1cZXlKalpYSjBhV1pwWTJGMFpTSTZleUoyWlhKemFXOXVJam94TENKelkyOXdaWE1pT2xzaVlYTnpkVzFsT214dloybHVMV2xrWlc1MGFYUjVPbWRwZEdoMVlpOHlPRFkzTTN4a2FtMXBkR05vWlNKZExDSnpkR0Z5ZENJNk1UWXdORFkzT1RVMU16TXlNeXdpWlhod2FYSjVJam94TmpBME5qZ3hNelV6TXpJekxDSnpaV1ZrSWpvaU1GTXpVV2x5V21kVVkwOVRVakZoV2t4a1QyMUJaMFpqZEhCaWJscGhVamQ1V1dRM1YzWlFSakZ3WkZFaUxDSnphV2R1WVhSMWNtVWlPaUpzVFVsaVdtUlhiR3g0YzJka1RYSTVRbE5qVjFVMU1XVTJiRWsyVW5SdWNqSTNla3QyZEdwTlFtZFZQU0lzSW1semMzVmxjaUk2SW5OMFlYUnBZeTkwWVhOclkyeDFjM1JsY2k5M1pXSXRjMlZ5ZG1WeUluMTk
```

and exactly as @ricky26 pointed out, the second of those contains a decoded URL, while the first does not!  So, I think I've finally replicated the correct bug :)

*digs into react router, etc.*

**Comment by djmitche** [comment] 2020-11-06 17:09
Confirmed on main, too (after fixing a bug introduced in #3844).

**Comment by djmitche** [comment] 2020-11-06 17:43
The URL from GraphQL query contains %2F (not encoded):
```
{
        "node": {
                "name": "public/logs/live_backing.log",
                "contentType": "text/plain; charset=utf-8",
                "url": "https://dustin.taskcluster-dev.net/api/queue/v1/task/WNfX_ZHtSaO-rarvsP2hOg/runs/0/artifacts/public%2Flogs%2Flive_backing.log?bewit=....",
                "isPublic": true,
                "isLog": true,
                "__typename": "Artifact"
        }
}
```

The path in the address bar encodes the whole URL (so, %252F)
https://dustin.taskcluster-dev.net/tasks/WNfX_ZHtSaO-rarvsP2hOg/runs/0/logs/https%3A%2F%2Fdustin.taskcluster-dev.net%2Fapi%2Fqueue%2Fv1%2Ftask%2FWNfX_ZHtSaO-rarvsP2hOg%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive_backing.log%3Fbewit%3DZ2...

On a router history change, match.params based on that path contains that encoded URL exactly (still %252F)
```
{
  "taskId": "WNfX_ZHtSaO-rarvsP2hOg",
  "runId": "0",
  "logUrl": "https%3A%2F%2Fdustin.taskcluster-dev.net%2Fapi%2Fqueue%2Fv1%2Ftask%2FWNfX_ZHtSaO-rarvsP2hOg%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log%3Fbewit%3Dc29tZXRoaW5nXDE2MDQ2ODM3ODlcam92NVppNXd5aUIzaUo2L3dYRmZUZldWd1FBcHZscUgyc0tSbXNOa0JRMD1c"
}
```

On reload, the path contains that encoded URL with doubly-encoded things like %252F only singly-encoded:
```
{
  "taskId": "WNfX_ZHtSaO-rarvsP2hOg",
  "runId": "0",
  "logUrl": "https%3A%2F%2Fdustin.taskcluster-dev.net%2Fapi%2Fqueue%2Fv1%2Ftask%2FWNfX_ZHtSaO-rarvsP2hOg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log%3Fbewit%3Dc29tZXRoaW5nXDE2MDQ2ODM3ODlcam92NVppNXd5aUIzaUo2L3dYRmZUZldWd1FBcHZscUgyc0tSbXNOa0JRMD1c"
}
```

I think that would come from doubly-decoding the URL parameter and then singly re-encoding it:

```
> encoded = "https%3A%2F%2Fdustin.taskcluster-dev.net%2Fapi%2Fqueue%2Fv1%2Ftask%2FWNfX_ZHtSaO-rarvsP2hOg%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log%3Fbewit%3Dc29tZXRoaW5nXDE2MDQ2ODM3ODlcam92NVppNXd5aUIzaUo2L3dYRmZUZldWd1FBcHZscUgyc0tSbXNOa0JRMD1c"
'https%3A%2F%2Fdustin.taskcluster-dev.net%2Fapi%2Fqueue%2Fv1%2Ftask%2FWNfX_ZHtSaO-rarvsP2hOg%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log%3Fbewit%3Dc29tZXRoaW5nXDE2MDQ2ODM3ODlcam92NVppNXd5aUIzaUo2L3dYRmZUZldWd1FBcHZscUgyc0tSbXNOa0JRMD1c'
> decodeURIComponent(encoded)
'https://dustin.taskcluster-dev.net/api/queue/v1/task/WNfX_ZHtSaO-rarvsP2hOg/runs/0/artifacts/public%2Flogs%2Flive.log?bewit=c29tZXRoaW5nXDE2MDQ2ODM3ODlcam92NVppNXd5aUIzaUo2L3dYRmZUZldWd1FBcHZscUgyc0tSbXNOa0JRMD1c'
> decodeURIComponent(decodeURIComponent(encoded))
'https://dustin.taskcluster-dev.net/api/queue/v1/task/WNfX_ZHtSaO-rarvsP2hOg/runs/0/artifacts/public/logs/live.log?bewit=c29tZXRoaW5nXDE2MDQ2ODM3ODlcam92NVppNXd5aUIzaUo2L3dYRmZUZldWd1FBcHZscUgyc0tSbXNOa0JRMD1c'
> encodeURIComponent(decodeURIComponent(decodeURIComponent(encoded)))
'https%3A%2F%2Fdustin.taskcluster-dev.net%2Fapi%2Fqueue%2Fv1%2Ftask%2FWNfX_ZHtSaO-rarvsP2hOg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log%3Fbewit%3Dc29tZXRoaW5nXDE2MDQ2ODM3ODlcam92NVppNXd5aUIzaUo2L3dYRmZUZldWd1FBcHZscUgyc0tSbXNOa0JRMD1c'
> 
```

I can confirm this is a react-router bug in a demo app.  In fact, it's a bit worse.

https://codesandbox.io/s/heuristic-sun-revzx?file=/src/App.js

**Comment by djmitche** [comment] 2020-11-06 17:49
It looks like this is a bug in react-history, that's been around for a long time and been "fixed" poorly.  I don't expect this to get "truly" fixed any time soon.

 * https://github.com/ReactTraining/history/issues/505
 * https://github.com/ReactTraining/history/issues/745

**Comment by ricky26** [comment] 2020-11-06 18:01
Reading the various issues on the history library (and some on react-router/react-router-dom) it sounds like that brokenness stems from the fact that browsers treat %-encoded URLs in `pushState` slightly differently.

Perhaps it's possible to avoid react-router-dom's `Link` for the log view (which would avoid `pushState`)? Granted, this would be a pretty unpleasant workaround.

The other workaround I can think of off-hand is to pass the log view URL parameter Base64 encoded, which would mean the URL wouldn't be readable at all. As a mitigation however, the log page does include a button which goes to the target URL (and displays it on error).

**Comment by djmitche** [comment] 2020-11-06 18:31
The result of `pushState` seems to be consistent and correct between browsers in this situation (`%252f` in both cases).

I think longer-term, we'll want to change how this works more substantially.  Generating URLs with a bewit and then passing them around in other URLs is pretty bizarre.  Once we have the object service, I think we could use URLs that contain only the artifact name, and the log viewer can use that value directly to request chunks of log data.  At that point, this would only be an issue for artifacts with names containing `%` (and assuming that history isn't fixed by then, we could continue to use the same workaround, or base64-encode only in that case).

**Closed** 2020-11-06 18:50 UTC
Labels: bug
