### ISSUE TITLE
[UI] Replace text field by MarkdownTextArea

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1387] opened 2019-09-24 17:40 UTC
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

This is the exact same issue as https://github.com/taskcluster/taskcluster/issues/1363 but for the description fields in
* https://taskcluster-ui.herokuapp.com/auth/roles/create
* https://taskcluster-ui.herokuapp.com/auth/clients/create
* https://taskcluster-ui.herokuapp.com/auth/roles/hook-id%3Ahg-push%2Fmozilla-esr60
* https://taskcluster-ui.herokuapp.com/auth/clients/email%2Fchinmaykousik1%40gmail.com%2Fgeneric-worker-test

**Comment by Rolikasi** [comment] 2019-10-02 09:02
Should we have the "Write" and "Preview" tabs?

**Comment by vishakhanihore** [comment] 2019-10-02 11:19
I think we are supposed to wait until the issue is assigned to us.

**Comment by Rolikasi** [comment] 2019-10-02 12:14
I live in UTC+6 timezone. I work on these issues during a day, because it's unproductive to wait until evening or night((

**Comment by vishakhanihore** [comment] 2019-10-02 12:31
Pretty same here +5:30

**Comment by djmitche** [comment] 2019-10-02 16:18
We want to make sure everyone gets a chance to work on an issue, and we don't have too many!  So let's save this for another applicant.  You can take a look at the other issues, not labeled "outreachy", and find one that looks good.  Those are likely to be a bit more challenging.

**Comment by Rolikasi** [comment] 2019-10-10 08:27
We can close this issue, because it was duplicated in #1459 and #1460 . And we all made PRs) 
Since I worked on this issue can I add it in my contribution records to the final application?)
Thanks!

**Comment by djmitche** [comment] 2019-10-10 13:49
Yes, that's fine..

**Closed** 2019-10-10 15:25 UTC
Labels: bug, good first issue, outreachy
