### ISSUE TITLE
[UI] Will-change memory consumption is too high

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1712] opened 2019-10-21 20:22 UTC
**To Reproduce**
1. Go to https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/groups/QKGlNKIWQYuiZ4hxDMrTTQ 
2. Open devtools
3. See error

![Screen Shot 2019-10-21 at 4 20 40 PM](https://user-images.githubusercontent.com/3766511/67240114-cdc5cf80-f41e-11e9-9631-5038eb8d439a.png)

**Expected behavior**
No warning in the console.

**Additional context**
I suspect this is coming from the virtual list that we use in the task group view but I'm not sure.

**Comment by vishakhanihore** [comment] 2019-10-22 18:53
@helfi92 Cant reproduce the same ?
<img width="1266" alt="Screenshot 2019-10-23 at 12 22 44 AM" src="https://user-images.githubusercontent.com/54327666/67319984-444ff380-f52b-11e9-9a62-6cd69e741617.png">

**Comment by helfi92** [comment] 2019-10-22 18:57
I forgot to mention that this issue only happens on Firefox.

**Comment by naimiii** [comment] 2019-10-23 13:29
@helfi92  can i get this issue as well ? :)

**Comment by helfi92** [comment] 2019-10-23 15:23
@naimiii I think you are assigned to https://github.com/taskcluster/taskcluster/issues/1684. We can have you assigned to this one after, if it's still available to grab. Thanks!

**Comment by THEozmic** [comment] 2019-10-23 15:55
I think the "will-change" attribute comes from Material UI. This attribute basically hints Firefox about  DOM modifications that are about to happen in order to improve optimization but Firefox informs us that it believes its optimizations would consume too much memory and so ignores it. It's not really an error and I don't think we can remove the warning since it's not coming from our code but from Material UI. You can see what I'm talking about in the screenshot:

![Screenshot 2019-10-23 16:54:37](https://user-images.githubusercontent.com/15184445/67411664-e3213200-f5b5-11e9-9d07-8aea86c5d7fc.png)

**Comment by vishakhanihore** [comment] 2019-10-23 16:07
@helfi92 The following issue has already been solved in MUI according to this commit https://github.com/mui-org/material-ui/pull/14036#issue-241493739 . I think since our MUI is not upgraded, I think an issue already opened for this and this can be closed safely.

**Comment by helfi92** [comment] 2019-10-23 18:34
@THEozmic Interesting. Thanks for looking into it.

@vishakhanihore From the linked comment:

> Affects the following components:
>
>    Slider
     ToggleButton
     CircularProgress
     Fade
     LinearProgress
     TabIndicator
     Zoom

Are we using any of those components in that table?

**Comment by THEozmic** [comment] 2019-10-24 13:06
After digging deeper into this, I've discovered that the issue is in fact not coming from Material UI as I earlier said. Material UI did have some issues with `will-change` but that has been fixed a long time ago and the version we are using contains that fix.

The `will-change` warning comes from `react-window` FixedSizeList component. I've been able to replicate the warning outside of `taskcluster` environment and saw that when I remove the `width: 100%` style from the List item, I no longer get that error.

I'm not sure what a good fix will be yet.

**Comment by vishakhanihore** [comment] 2019-10-24 19:13
> After digging deeper into this, I've discovered that the issue is in fact not coming from Material UI as I earlier said. Material UI did have some issues with `will-change` but that has been fixed a long time ago and the version we are using contains that fix.
> 
> The `will-change` warning comes from `react-window` FixedSizeList component. I've been able to replicate the warning outside of `taskcluster` environment and saw that when I remove the `width: 100%` style from the List item, I no longer get that error.
> 
> I'm not sure what a good fix will be yet.

Great observation @THEozmic

**Comment by naimiii** [comment] 2019-10-24 20:55
@helfi92  Can i get this issue now ? :)

**Comment by km-js** [comment] 2019-10-24 23:49
Hey @helfi92 and @THEozmic . I have  looked a bit into this issue and think as already stated by @THEozmic , the warning is coming from the react-window's component FixedSizeList as I checked out the code and found the `willChange` property there.
![Screenshot_43](https://user-images.githubusercontent.com/39799586/67532089-9a1acc00-f6e2-11e9-954b-275ab01898e5.png)

Just wondering if overriding the `willChange` property to auto in our component can help fix the issue.

**Comment by vishakhanihore** [comment] 2019-10-24 23:52
A better solution I think would be to create a issue in the library and
send our patch over there. @helfi92?

**Comment by THEozmic** [comment] 2019-10-24 23:53
@km-js, Overriding it might not be the best because it offers performance optimizations. What the warning is telling us is that given a certain number of DOM elements associated with the required optimizations, the resource needed to perform those optimizations do not justify the gains that might be made, hence no optimizations will be made. But that's not always the case, sometimes the optimization gains justify the resources used.

**Comment by THEozmic** [comment] 2019-10-24 23:58
I know that if we remove the `height` property on the element's class, we won't get that warning. This is because there's more element being rendered at a time if the height is set to `100%`  versus if it's set to `window.innerHeight` as we see here.

**Comment by helfi92** [comment] 2019-10-25 13:32
Thanks for digging into this everyone. I'm not sure if overriding the `willChange` property is the best thing to do since it might affects performance of the virtual list.

I agree that the culprit is

https://github.com/taskcluster/taskcluster/blob/d4c576a7cd0bd843e0bf5e7d462b511fd44bf46c/ui/src/components/TaskGroupTable/index.jsx#L140-L142

Using something like `window.innerHeight` would make sense but that currently adds an extra scroller which we don't want:

![Screen Shot 2019-10-25 at 9 28 48 AM](https://user-images.githubusercontent.com/3766511/67575123-ddd4fc00-f709-11e9-9326-b473678fd5c9.png)
 
Perhaps we just need a bigger value than window.innerHeight? I'm not sure. I think we are on the right track to finding a solution :)

**Comment by lotas** [comment] 2022-05-13 09:04
I will close this, as it is no longer an issue, checked in Safari and Firefox

**Closed by lotas** 2022-05-13 09:04 UTC
Labels: good first issue, ui
