### ISSUE TITLE
All docs show an error

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1842] opened 2019-10-31 02:17 UTC
**Describe the bug**
API reference pages are showing an error message, and no references.

**To Reproduce**

1. Go to https://docs.taskcluster.net/docs/reference/platform/queue/api
1. See error: `Unexpected token (6:14)`

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/28673/67913293-f22e5400-fb62-11e9-98ad-44e256049fa4.png)

**Additional context**
This error appears to be "sticky" -- any other docs pages will also fail to render after seeing this error.

The bug has been introduced since v21.2.0, as that version renders the documentation correctly.

**Comment by vishakhanihore** [comment] 2019-10-31 04:42
Looking into it

**Comment by vishakhanihore** [comment] 2019-10-31 04:50
@djmitche Nice to note things is that, if one page breaks, all the other pages breaks too !

**Comment by naima-shaikh** [comment] 2019-10-31 06:47
@djmitche  I m looking into it .It seem's interesting  to fix .Can you plz assign me this one ?

**Comment by djmitche** [comment] 2019-10-31 13:00
@naima-shaikh I can, but we do need this fixed soon -- we need to make another release of TC, with this fixed.  If you can fix it in, say, the next 24 hours that would be great..

**Comment by djmitche** [comment] 2019-10-31 13:00
(if not, that's fine to, just let us know)

**Comment by naima-shaikh** [comment] 2019-10-31 13:14
@djmitche  thanks for assigning it to me . I will try to fix it within 24 hours :)

**Comment by vishakhanihore** [comment] 2019-10-31 13:34
Please let me know if you are unable yo solve it , I have already debugged
the following, will also send the patch if you can not.
@naima-shaikh

**Comment by helfi92** [comment] 2019-10-31 13:39
Note that there is already an issue and a pull-request open to fix the error panel positioning. https://github.com/taskcluster/taskcluster/issues/1660

**Comment by vishakhanihore** [comment] 2019-10-31 13:46
Cool but I dont think the error would be anyway related to the following
PR😅

**Comment by naima-shaikh** [comment] 2019-10-31 14:30
@djmitche  @vishakhanihore 
I can't seem to reproduce this issue running locally http://localhost:5080/docs/reference/platform/auth/api shows no error panel. Is this issue only occuring in production and if so how can I point to production stack locally?

**Comment by naima-shaikh** [comment] 2019-10-31 14:48
@helfi92  Sorry . i m doing it now :)

**Comment by vishakhanihore** [comment] 2019-11-01 15:02
@naima-shaikh Any Progress ?

**Comment by naima-shaikh** [comment] 2019-11-01 15:48
@vishakhanihore  This issue is  already fixed  by @djmitche  with a similar logic :)

**Comment by vishakhanihore** [comment] 2019-11-01 15:54
@djmitche is this fixed?

**Comment by djmitche** [comment] 2019-11-01 16:05
Sorry, I fixed a different bug in #1849 and pinged @naima-shaikh.  That was my fault.  It's not fixed.

**Comment by naima-shaikh** [comment] 2019-11-01 16:47
@djmitche  Alright thanks for informing :) .let me look into it again .

**Comment by vishakhanihore** [comment] 2019-11-01 17:13
@naima-shaikh , feel free to collaborate with me if you are stuck anywhere.
Two is always better than one😁

**Comment by helfi92** [comment] 2019-11-01 17:46
https://github.com/taskcluster/taskcluster/commit/905228f94afdb892d56333d678310ee0beb67f6d seems to be the culprit.

**Comment by vishakhanihore** [comment] 2019-11-01 18:07
@helfi92 rather than reverting to lower version, cant we disable ESlint for
this 4 lines ?

**Comment by helfi92** [comment] 2019-11-01 18:30
@vishakhanihore Which 4 lines?

**Comment by vishakhanihore** [comment] 2019-11-01 18:32
The place where its showing unexpected token error line 6-10?

**Closed** 2019-11-01 18:33 UTC
Labels: bug

**Comment by helfi92** [comment] 2019-11-01 18:47
> The place where its showing unexpected token error line 6-10?

I'm not sure where which line 6-10 that is. I will file an issue soon to have the UI migrated to eslint v6.

**Comment by djmitche** [comment] 2019-11-01 18:51
I'm super-confused how eslint -- which is a devDependency -- could cause a failure at runtime.

**Comment by helfi92** [comment] 2019-11-01 20:42
Probably because of https://github.com/taskcluster/taskcluster/pull/1863/files#diff-41c7b0973853207d6085c8df75e6dc50R1629.

**Comment by djmitche** [comment] 2019-11-01 21:01
:boggle:
