### ISSUE TITLE
New UI: Add notify on task group success

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#305] opened 2019-02-25 20:20 UTC
Similar to #304 it's useful to know when a task group is completed in addition to the green status icon in the tab icon.

Making this another opt-in feature would probably work.

**Comment by sudipt1999** [comment] 2019-03-02 10:36
Can I work on this @jonalmeida  !Some pointers would be really helpful!

**Comment by helfi92** [comment] 2019-03-02 15:25
@sudipt1999 We should wait until we have a setting view before we decide to implement this feature. Feel free to tackle another issue :)

**Comment by ccooper** [comment] 2019-05-31 14:22
Duplicate of #304 

I think we would tackle both types of notifications at the same time.

**Closed by ccooper** 2019-05-31 14:22 UTC
Labels: ui
