### ISSUE TITLE
worker-runner 32.0.0 seems not to reregister static worker

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#3356] opened 2020-08-06 12:58 UTC
**Describe the bug**
Our [mac worker](https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ci-macos/workers/proj-taskcluster/63-135-170-250) has gone offline with the failure message in the logs:

```
2020/08/05 13:52:25 Loading worker-runner configuration from /etc/generic-worker/runner.yml
2020/08/05 13:52:25 Configuring with provider static
2020/08/05 13:52:26 Could not register worker: 
CALL SUMMARY
============
Method: POST
Service: community-tc.services.mozilla.com:
Response Body:
{
  "code": "InputError",
  "message": "Worker proj-taskcluster/63-135-170-250 has expired\n\n---\n\n* method:     registerWorker\n* errorCode:  InputError\n* statusCode: 400\n* time:       2020-08-05T17:52:26.687Z",
  "requestInfo": {
    "method": "registerWorker",
    "params": {},
    "payload": "(OMITTED)",
    "time": "2020-08-05T17:52:26.687Z"
  }
}
Attempts: 1
(Permanent) HTTP response code 400
HTTP/2.0 400 Bad Request
Content-Length: 358
Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,Accept,Origin,Cache-Control
Access-Control-Allow-Methods: OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 900
Access-Control-Request-Method: *
Alt-Svc: clear
Cache-Control: no-store no-cache must-revalidate
Content-Security-Policy: report-uri /__cspreport__;default-src 'none';frame-ancestors 'none';
Content-Type: application/json; charset=utf-8
Date: Wed, 05 Aug 2020 17:52:26 GMT
Etag: W/"166-CaBdMIN7K84lJDEWcndixASfNto"
Server: openresty
Strict-Transport-Security: max-age=31536000
Via: 1.1 google
X-Content-Type-Options: nosniff
X-For-Request-Id: 128171eb-d87a-4040-8567-e5c2948285dd
X-For-Trace-Id: a15737a52764d11a83fbe979b2d3be3a

{
  "code": "InputError",
  "message": "Worker proj-taskcluster/63-135-170-250 has expired\n\n---\n\n* method:     registerWorker\n* errorCode:  InputError\n* statusCode: 400\n* time:       2020-08-05T17:52:26.687Z",
  "requestInfo": {
    "method": "registerWorker",
    "params": {},
    "payload": "(OMITTED)",
    "time": "2020-08-05T17:52:26.687Z"
  }
}
``` 

This suggests that the worker reregistration and updating of generic-worker taskcluster credentials that worker-runner performs has not worked.

Reregistration in worker-runner was released in v31.0.0 in #3073 which landed in release 31.0.0. Worker runner 32.0.0 and generic-worker 32.0.0 are deployed on worker `proj-taskcluster/63-135-170-250`, so automatic worker reregistration should work.

**Taskcluster version**
32.0.0

**Comment by petemoore** [comment] 2020-08-06 13:05
Worker logs from last successful run show:

```
2020/08/05 11:04:24 Loading worker-runner configuration from /etc/generic-worker/runner.yml
2020/08/05 11:04:24 Configuring with provider static
2020/08/05 11:04:25 Identified as worker proj-taskcluster/63-135-170-250
2020/08/05 11:04:25 Getting secrets from secrets service
2020/08/05 11:04:25 WARNING: No worker secrets for worker pool proj-taskcluster/gw-ci-macos.
2020/08/05 11:04:25 Configuring for worker implementation generic-worker
2020/08/05 11:04:25 provider metadata public-ipv4 not available; not setting config publicIp
2020/08/05 11:04:25 provider metadata local-ipv4 not available; not setting config privateIP
2020/08/05 11:04:25 provider metadata instance-type not available; not setting config instanceType
2020/08/05 11:04:25 provider metadata instance-id not available; not setting config instanceID
2020/08/05 11:04:25 provider metadata region not available; not setting config region
2020/08/05 11:04:25 provider metadata availability-zone not available; not setting config availabilityZone
2020/08/05 11:04:25 Writing files
2020/08/05 11:04:25 Starting worker
2020/08/05 11:04:25 Worker credentials expire in 720h0m0s
2020/08/05 11:04:25 Loading generic-worker config file '/etc/generic-worker/config'...
2020/08/05 11:04:25 Config: {
  "availabilityZone": "",
  "cachesDir": "/Library/Caches/generic-worker/caches",
  "checkForNewDeploymentEverySecs": 1800,
  "cleanUpTaskDirs": true,
  "clientId": "worker/static/proj-taskcluster/gw-ci-macos/proj-taskcluster/63-135-170-250",
  "deploymentId": "",
  "disableReboots": false,
  "downloadsDir": "/Library/Caches/generic-worker/downloads",
  "ed25519SigningKeyLocation": "/etc/generic-worker/ed25519_key",
  "idleTimeoutSecs": 0,
  "instanceId": "",
  "instanceType": "",
  "livelogExecutable": "/usr/local/bin/livelog",
  "numberOfTasksToRun": 0,
  "privateIP": "",
  "provisionerId": "proj-taskcluster",
  "publicIP": "63.135.170.250",
  "region": "",
  "requiredDiskSpaceMegabytes": 20480,
  "rootURL": "https://community-tc.services.mozilla.com",
  "runAfterUserCreation": "",
  "runTasksAsCurrentUser": true,
  "sentryProject": "generic-worker",
  "shutdownMachineOnIdle": false,
  "shutdownMachineOnInternalError": false,
  "taskclusterProxyExecutable": "/usr/local/bin/taskcluster-proxy",
  "taskclusterProxyPort": 8080,
  "tasksDir": "/Users",
  "workerGroup": "proj-taskcluster",
  "workerId": "63-135-170-250",
  "workerType": "gw-ci-macos",
  "workerTypeMetadata": {
    "config": {
      "deploymentId": ""
    },
    "generic-worker": {
      "engine": "multiuser",
      "go-arch": "amd64",
      "go-os": "darwin",
      "go-version": "go1.13.7",
      "release": "https://github.com/taskcluster/taskcluster/releases/tag/v32.0.0",
      "revision": "10ff5bc4ddb9387cc44ae0131872f88e80cf3c10",
      "source": "https://github.com/taskcluster/taskcluster/commits/10ff5bc4ddb9387cc44ae0131872f88e80cf3c10",
      "version": "32.0.0"
    }
  },
  "wstAudience": "communitytc",
  "wstServerURL": "https://community-websocktunnel.services.mozilla.com"
}
```

**Comment by djmitche** [comment] 2020-08-06 18:14
```
  "message": "Worker proj-taskcluster/63-135-170-250 has expired\n\n---\n\n* method:     registerWorker\n* errorCode:  InputError\n* statusCode: 400\n* time:       2020-08-05T17:52:26.687Z",
```

This isn't credential expiration -- it is trying to re-register, but the expiration time has passed.

I think this is a dupe of #3352.  I'll re-create the worker.

**Closed by djmitche** 2020-08-06 18:14 UTC
Labels: bug

**Comment by djmitche** [comment] 2020-08-06 18:45
(it's running tasks now)
