### ISSUE TITLE
[UI] pop-up menu items not aligned

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1874] opened 2019-11-03 19:56 UTC
**Describe the bug**
The items in the pop-up menu in the lower right are not aligned

**To Reproduce**

1. Go to a https://community-tc.services.mozilla.com/tasks/KdwFUTxUTiWiHoRDBYhEmA/runs/0
2. Hover over the thing in the lower right

**Expected behavior**
Aligned items

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/28673/68091144-12536100-fe4a-11e9-8c30-719243a9e5ca.png)

**Comment by djmitche** [comment] 2019-11-03 20:00
If they do line up for you, un-hover and hover again.  They move every time!!

**Comment by ajinkabeer** [comment] 2019-11-04 04:30
Can I take a look at this please?
@djmitche

**Comment by naima-shaikh** [comment] 2019-11-04 06:16
@djmitche  can I  get it. If it's free ?

**Comment by ajinkabeer** [comment] 2019-11-04 06:20
Oh, its okay if you want to work on it, please go on. @naima-shaikh @djmitche

**Comment by naima-shaikh** [comment] 2019-11-04 07:08
@ajinkabeer  It will decide by @djmitche   that who will work on it . :)  I was just asking  :)

**Comment by djmitche** [comment] 2019-11-04 13:34
That's very gracious of you @ajinkabeer -- I did fix something i had assigned to @naima-shaikh a few days ago, so I'll give this issue to them.

Note that I have no idea how to fix this!

**Comment by ajinkabeer** [comment] 2019-11-04 13:38
> That's very gracious of you @ajinkabeer -- I did fix something i had assigned to @naima-shaikh a few days ago, so I'll give this issue to them.
> 
> Note that I have no idea how to fix this!

Totally cool!! :) @djmitche

**Comment by naima-shaikh** [comment] 2019-11-04 13:51
@djmitche  Thank you :)

**Comment by helfi92** [comment] 2019-11-04 16:15
Hmm, I'm not able to replicate. @naima-shaikh are you able to replicate the issue?

**Comment by naima-shaikh** [comment] 2019-11-04 16:56
@helfi92  @djmitche  Is this issue a browser specific ?

**Comment by naima-shaikh** [comment] 2019-11-04 17:07
@helfi92  I m trying my best :)

**Comment by naima-shaikh** [comment] 2019-11-04 17:24
@djmitche  @helfi92  When i run from the provided link this is how it shows on my machine
![74241440_860963600971888_4778266410902093824_n (1)](https://user-images.githubusercontent.com/28563415/68142769-e15e5380-ff51-11e9-8e93-eeeda63765c3.png)

**Comment by djmitche** [comment] 2019-11-04 17:51
Could it have to do with window width?  My window is *very* wide..

**Comment by djmitche** [comment] 2019-11-04 17:52
Hm, no, I can replicate even on a window only 1899 pixels wide.  Try rolling over the button a bunch to render and un-render the menu.

**Comment by djmitche** [comment] 2019-11-04 17:53
I'm on Firefox 70.

**Comment by naima-shaikh** [comment] 2019-11-04 18:32
@djmitche  I tried it in Firefox  on a wide screen and still could not reproduce :( 
![74183538_460864514777529_5703551178487365632_n](https://user-images.githubusercontent.com/28563415/68147193-5d10ce00-ff5b-11e9-8072-cb3e00ab085c.png)

**Comment by helfi92** [comment] 2019-11-04 18:54
@djmitche Is the behavior intermittent?

**Comment by djmitche** [comment] 2019-11-04 18:56
Yes (weird!!)

**Comment by helfi92** [comment] 2019-11-04 21:16
Ah, that's most probably a material-ui bug. This might be fixed in v4 after https://github.com/taskcluster/taskcluster/pull/1729 is merged.

**Closed** 2019-11-25 17:59 UTC
Labels: blocked, bug
