### ISSUE TITLE
New UI: The menu on the left should be foldable/hideable

### ISSUE THREAD

**Issue by glandium** [taskcluster/taskcluster#249] opened 2019-02-15 01:00 UTC
The menu on the left takes precious horizontal space, and it can be useful to hide it or make it smaller in some views, like the live log view, or the task view.

**Comment by helfi92** [comment] 2019-02-15 12:48
Duplicate of https://github.com/taskcluster/taskcluster/issues/225.

**Closed by helfi92** 2019-02-15 12:48 UTC
Labels: ui
