### ISSUE TITLE
[UI] Live log view doesn't have horizontal scrolling.

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#2122] opened 2019-12-02 19:46 UTC
**Describe the bug**

Can't scroll horizontally to see a long log line.

**To Reproduce**

1. Go to [these logs](https://firefox-ci-tc.services.mozilla.com/tasks/DcMDbrHATk61uuVLfoqacQ/runs/0/logs/live/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FDcMDbrHATk61uuVLfoqacQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log).
3. Scroll down to `Error: Matrix failed: matrix-374yonwtugoxf FINISHED failure`
4. Try to scroll horizontally.

**Expected behavior**

To be able to select the full URL in the logs.

**Taskcluster version**

**Screenshots**

**Platform (please complete the following information):**

 - OS: Mac OS
 - Browser if applicable: Firefox Nightly 72.0a1 (2019-11-18) (64-bit)
 - Version if applicable: Taskcluster UI v23.0.0

**Comment by helfi92** [comment] 2019-12-02 20:06
Duplicate of https://github.com/taskcluster/taskcluster/issues/1997. This has been fixed in v24.0.0.

**Comment by helfi92** [comment] 2019-12-02 20:09
Duplicate of https://github.com/taskcluster/taskcluster/issues/1997.

This has been fixed in v24.0.0.

**Closed** 2019-12-02 20:09 UTC
Labels: bug
