### ISSUE TITLE
When rerunning a failed action, the github check doesn't go back from failed to running

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5085] opened 2022-01-26 12:17 UTC
Run an action from the github integration that fails, rerun it from the taskcluster interface, the github check stays failed instead of going back to running.

**Comment by escapewindow** [comment] 2022-02-16 16:53
This is also causing the MoCo mobile team issues since they often have a failing task they need to rerun to merge a PR.

**Comment by jonalmeida** [comment] 2022-08-09 18:34
I see some merged changes linked to this bug, but I'm still seeing facing this issue in mozilla-mobile/android-components with tasks that are re-run, and then put in the the pending state on TC, but not reflected in the Github UI.

**Comment by lotas** [comment] 2022-08-09 19:16
hey @jonalmeida thanks for letting us know. This needs a bit more testing, I got stuck with missing roles and discussions who should configure those. This is also part of our priorities for this quarter. Hopefully it will be working soon

**Comment by lotas** [comment] 2022-08-11 15:37
@jonalmeida quick update from my side, I was just fixing something related in github integration and also tested 're-run' functionality: #5617 

It worked for me, but I had to make few tweaks:
- before it didn't send an error message properly if TC was setup incorrectly (missing scopes). Now taskcluster bot should send a comment with a detailed error message.
- you need to make sure that taskcluster is configured properly: it should have a role which allows tasks to be rerun. This can either be through a generic `repo:github.com/org/repo:*` role, or dedicated role `repo:github.com/org/repo:rerun`, that will allow `queue:rerun-task:*` and `queue:rerun-task-in-project:*`

By looking at [current scopes](https://firefox-ci-tc.services.mozilla.com/auth/scopes/expansions?scopes%5B0%5D=assume%3Arepo%3Agithub.com%2Fmozilla-mobile%2Fandroid-components%3A%2A) I think it is missing the `queue:rerun-task-in-project:*` scope

Upd: checking service logs, I see this:

```
Client ID static/taskcluster/github does not have sufficient scopes and is missing the following scopes:

{
  "AnyOf": [
    "queue:rerun-task:mobile-level-1/KRO4xszhSze7HeQF7wB6Rg/M4rbApUATVC7XIGwpT6Q9g",
    "queue:rerun-task-in-project:none",
    {
      "AllOf": [
        "queue:rerun-task",
        "assume:scheduler-id:mobile-level-1/KRO4xszhSze7HeQF7wB6Rg"
      ]
    }
  ]
}
```

So that confirms that `queue:rerun-task-in-project:none` is missing indeed. I'm not sure who manages configuration there and who can help you add this missing role. @ahal do you know? :)
Thanks

**Comment by ahal** [comment] 2022-08-11 16:26
I'm a bit confused, it sounded like `reruns` were working for folks but just weren't updating Github properly? Or are you saying that your changes now require new scopes? A link to a task that hits the scope expression error would be helpful for me.

**Comment by lotas** [comment] 2022-08-11 16:46
Reruns were working properly through cli/web ui, but not from Github pages. We added support for the `rerun` event that happens when someone clicks "Re-run" on a failed task in PR. And for this scenario, github repo needs to have roles that would allow to rerun the task.. Yeah, it's complicated :)

**Comment by Eijebong** [comment] 2022-08-11 17:19
FYI, when I opened this issue it was about the status not getting updated when rerunning a task (from the taskcluster UI), it wasn't about the github retry button not working.

**Comment by jonalmeida** [comment] 2022-08-11 17:29
> FYI, when I opened this issue it was about the status not getting updated when rerunning a task (from the taskcluster UI), it wasn't about the github retry button not working.

Yes, to add clarity from myself too: it was about the status, not the ability to re-run from the GitHub UI.

**Comment by lotas** [comment] 2022-08-11 20:02
@Eijebong @jonalmeida oops, my bad. I missed that part :) Was focused on the other side of it, will have a look

**Comment by lotas** [comment] 2022-08-11 21:19
upd: tested this scenario locally and "it works on my machine" :D  
If I rerun task locally, it sends back all statuses back to github, and I observed status of the build going from failed to succeeded. Maybe still some permission issues? Will have to debug on one of the broken repos then

**Comment by jonalmeida** [comment] 2022-08-11 22:06
@lotas to avoid any ambiguity, I've written down some STR below and highlighted the parts in the results that is the current bug I (and probably also @Eijebong) is referring to. How this helps:

### Steps to reproduce
1. Have a task that has succeed or failed.
2. Observe in Github UI.
3. Re-run the task.
4. Before the task starts running, observe in Github UI.
5. When the task starts running, observe in Github UI.
6. After the task is complete, observe in Github UI.

### Expected results
- At step 2, the task shows up as successful or failed.
- At step 4, the task shows up as **pending**.
- At step 5, the task shows up as running.
- At step 6, the task shows up as completed (successful or failed).

### Actual results
- At step 2, the task shows up as successful or failed.
- At step 4, the task shows up as **successful or failed (no change from step 2)**.
- At step 5, the task shows up as running.
- At step 6, the task shows up as completed (successful or failed).

**Comment by lotas** [comment] 2022-08-12 06:02
@jonalmeida thanks, that helps :) 

Okay, so the problem we are trying to solve here is that once the status was set to completed with any result, it will only stay in this state until resolved to success/fail again. 
And this is actually what code is doing, it only listens to `task-failed` and `task-completed` events :) 
So that's why any other states are not being reported 🤦  Gonna add more states :+1:

**Comment by lotas** [comment] 2022-08-12 11:57
Things are getting more interesting here .. :) Turns out, this is a feature according to [this comment](https://github.com/orgs/community/discussions/24761#discussioncomment-3245360)
> Once a check run transitions from the in_progress state to completed state, it’s not possible to modify its status nor its conclusion further

Okay, so we cannot simply patch the status, instead we need to trigger [rerequestRun](https://docs.github.com/en/rest/checks/runs#rerequest-a-check-run) endpoint, so github would reset status back to `queued` and erase the `conclusion` status.

The problem here is that it generates same event as we already have in the UI when someone clicks "re-run". And it will go into endless loop (tc will run a task, tell gh to reset status, gh will tell that this reset wants to restart a job, tc will restart a job.. and so it will go forever)
I need to think how to prevent this. One idea that comes to mind is checking the `sender` of the event. If this was triggered by TC, `sender` would contain bot's name.

I'm not 100 sure this is what we want to do.. maybe we want to create a new check run instead?

**Comment by lotas** [comment] 2022-08-18 14:26
This is very likely fixed already, will be testing on dev/stage. 

Problem was two-fold: 
1. github doesn't allow to update status of check runs that were resolved already (necessary to call `rerequestRun`)
2. taskcluster's github service was not listening for all status updates, only resolved/errored ones. I've added queued/in_progress listeners, and logic to rerequest check run

**Comment by lotas** [comment] 2022-08-26 08:35
I am still testing this, looks like there are some extra unknowns, doesn't always work still

**Comment by jonalmeida** [comment] 2023-05-09 19:02
I've noticed that a taskcluster 're-run' action is now being reflected in the Github status checks. Feel free to close this issue if that is enough verification. :)

**Comment by lotas** [comment] 2023-05-09 19:21
hey @jonalmeida thanks for reminding about this issue :)
Yeah, I think we can close it unless you have some evidence it is still not working. We've done so many fixes to both checks and statuses apis, it should really be working 🤞

**Closed** 2023-05-09 19:21 UTC
Labels: bug, contributor-request
